#!/usr/bin/env bash
#
# Commit Claude's changes and push the working branch.
#
# Reads (env): BRANCH, TICKET_KEY, TICKET_SUMMARY
set -euo pipefail

git add -A
git commit \
  -m "${TICKET_KEY}: ${TICKET_SUMMARY}" \
  -m "Generated by Claude Code from JIRA ticket ${TICKET_KEY}."
git push origin "$BRANCH"
